

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CloudBreadAdminWeb
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class CloudBreadDBAdminEntities : DbContext
{
    public CloudBreadDBAdminEntities()
        : base("name=CloudBreadDBAdminEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<AdminMembers> AdminMembers { get; set; }

    public virtual DbSet<CloudBreadAdminLog> CloudBreadAdminLog { get; set; }

    public virtual DbSet<CloudBreadErrorLog> CloudBreadErrorLog { get; set; }

    public virtual DbSet<CloudBreadLog> CloudBreadLog { get; set; }

    public virtual DbSet<Coupon> Coupon { get; set; }

    public virtual DbSet<CouponMember> CouponMember { get; set; }

    public virtual DbSet<GameEventMember> GameEventMember { get; set; }

    public virtual DbSet<GameEvents> GameEvents { get; set; }

    public virtual DbSet<GiftDepositories> GiftDepositories { get; set; }

    public virtual DbSet<ItemLists> ItemLists { get; set; }

    public virtual DbSet<MemberAccountBlockLog> MemberAccountBlockLog { get; set; }

    public virtual DbSet<MemberGameInfoes> MemberGameInfoes { get; set; }

    public virtual DbSet<MemberGameInfoStages> MemberGameInfoStages { get; set; }

    public virtual DbSet<MemberItemPurchases> MemberItemPurchases { get; set; }

    public virtual DbSet<MemberItems> MemberItems { get; set; }

    public virtual DbSet<Members> Members { get; set; }

    public virtual DbSet<Notices> Notices { get; set; }

    public virtual DbSet<ServerInfo> ServerInfo { get; set; }

    public virtual DbSet<Sessions> Sessions { get; set; }

    public virtual DbSet<StatsData> StatsData { get; set; }

}

}

