//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudBread_Admin_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coupon
    {
        public string CouponID { get; set; }
        public string CouponCategory1 { get; set; }
        public string CouponCategory2 { get; set; }
        public string CouponCategory3 { get; set; }
        public string ItemListID { get; set; }
        public string ItemCount { get; set; }
        public string ItemStatus { get; set; }
        public string TargetGroup { get; set; }
        public string TargetOS { get; set; }
        public string TargetDevice { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public string sCol1 { get; set; }
        public string sCol2 { get; set; }
        public string sCol3 { get; set; }
        public string sCol4 { get; set; }
        public string sCol5 { get; set; }
        public string sCol6 { get; set; }
        public string sCol7 { get; set; }
        public string sCol8 { get; set; }
        public string sCol9 { get; set; }
        public string sCol10 { get; set; }
        public string DupeYN { get; set; }
        public int OrderNumber { get; set; }
        public System.DateTimeOffset CouponDurationFrom { get; set; }
        public System.DateTimeOffset CouponDurationTo { get; set; }
        public string CreateAdminID { get; set; }
        public string HideYN { get; set; }
        public string DeleteYN { get; set; }
        public System.DateTimeOffset CreatedAt { get; set; }
        public System.DateTimeOffset UpdatedAt { get; set; }
        public string DataFromRegion { get; set; }
        public System.DateTimeOffset DataFromRegionDT { get; set; }
    }
}
