//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudBread_Admin_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberItemPurchases
    {
        public string MemberItemPurchaseID { get; set; }
        public string MemberID { get; set; }
        public string ItemListID { get; set; }
        public string PurchaseQuantity { get; set; }
        public string PurchasePrice { get; set; }
        public string PGinfo1 { get; set; }
        public string PGinfo2 { get; set; }
        public string PGinfo3 { get; set; }
        public string PGinfo4 { get; set; }
        public string PGinfo5 { get; set; }
        public string PurchaseDeviceID { get; set; }
        public string PurchaseDeviceIPAddress { get; set; }
        public string PurchaseDeviceMACAddress { get; set; }
        public string PurchaseDT { get; set; }
        public string PurchaseCancelYN { get; set; }
        public string PurchaseCancelDT { get; set; }
        public string PurchaseCancelingStatus { get; set; }
        public string PurchaseCancelReturnedAmount { get; set; }
        public string PurchaseCancelDeviceID { get; set; }
        public string PurchaseCancelDeviceIPAddress { get; set; }
        public string PurchaseCancelDeviceMACAddress { get; set; }
        public string sCol1 { get; set; }
        public string sCol2 { get; set; }
        public string sCol3 { get; set; }
        public string sCol4 { get; set; }
        public string sCol5 { get; set; }
        public string sCol6 { get; set; }
        public string sCol7 { get; set; }
        public string sCol8 { get; set; }
        public string sCol9 { get; set; }
        public string sCol10 { get; set; }
        public string HideYN { get; set; }
        public string DeleteYN { get; set; }
        public string PurchaseCancelConfirmAdminMemberID { get; set; }
        public System.DateTimeOffset CreatedAt { get; set; }
        public System.DateTimeOffset UpdatedAt { get; set; }
        public string DataFromRegion { get; set; }
        public System.DateTimeOffset DataFromRegionDT { get; set; }
    }
}
