
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CloudBreadAdminWeb
{

using System;
    using System.Collections.Generic;
    
public partial class MemberGameInfoStages
{

    public string MemberGameInfoStageID { get; set; }

    public string MemberID { get; set; }

    public string StageName { get; set; }

    public string StageStatus { get; set; }

    public string Category1 { get; set; }

    public string Category2 { get; set; }

    public string Category3 { get; set; }

    public string Mission1 { get; set; }

    public string Mission2 { get; set; }

    public string Mission3 { get; set; }

    public string Mission4 { get; set; }

    public string Mission5 { get; set; }

    public string Points { get; set; }

    public string StageStat1 { get; set; }

    public string StageStat2 { get; set; }

    public string StageStat3 { get; set; }

    public string StageStat4 { get; set; }

    public string StageStat5 { get; set; }

    public string sCol1 { get; set; }

    public string sCol2 { get; set; }

    public string sCol3 { get; set; }

    public string sCol4 { get; set; }

    public string sCol5 { get; set; }

    public string sCol6 { get; set; }

    public string sCol7 { get; set; }

    public string sCol8 { get; set; }

    public string sCol9 { get; set; }

    public string sCol10 { get; set; }

    public string HideYN { get; set; }

    public string DeleteYN { get; set; }

    public System.DateTimeOffset CreatedAt { get; set; }

    public System.DateTimeOffset UpdatedAt { get; set; }

    public string DataFromRegion { get; set; }

    public System.DateTimeOffset DataFromRegionDT { get; set; }

}

}
