//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudBread_Admin_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberGameInfoes
    {
        public string MemberID { get; set; }
        public string Level { get; set; }
        public string Exps { get; set; }
        public string Points { get; set; }
        public string UserSTAT1 { get; set; }
        public string UserSTAT2 { get; set; }
        public string UserSTAT3 { get; set; }
        public string UserSTAT4 { get; set; }
        public string UserSTAT5 { get; set; }
        public string UserSTAT6 { get; set; }
        public string UserSTAT7 { get; set; }
        public string UserSTAT8 { get; set; }
        public string UserSTAT9 { get; set; }
        public string UserSTAT10 { get; set; }
        public string sCol1 { get; set; }
        public string sCol2 { get; set; }
        public string sCol3 { get; set; }
        public string sCol4 { get; set; }
        public string sCol5 { get; set; }
        public string sCol6 { get; set; }
        public string sCol7 { get; set; }
        public string sCol8 { get; set; }
        public string sCol9 { get; set; }
        public string sCol10 { get; set; }
        public string HideYN { get; set; }
        public string DeleteYN { get; set; }
        public System.DateTimeOffset CreatedAt { get; set; }
        public System.DateTimeOffset UpdatedAt { get; set; }
        public string DataFromRegion { get; set; }
        public System.DateTimeOffset DataFromRegionDT { get; set; }
    }
}
