//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudBread_Admin_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notices
    {
        public string NoticeID { get; set; }
        public string NoticeCategory1 { get; set; }
        public string NoticeCategory2 { get; set; }
        public string NoticeCategory3 { get; set; }
        public string TargetGroup { get; set; }
        public string TargetOS { get; set; }
        public string TargetDevice { get; set; }
        public string NoticeImageLink { get; set; }
        public string title { get; set; }
        public string content { get; set; }
        public string sCol1 { get; set; }
        public string sCol2 { get; set; }
        public string sCol3 { get; set; }
        public string sCol4 { get; set; }
        public string sCol5 { get; set; }
        public string sCol6 { get; set; }
        public string sCol7 { get; set; }
        public string sCol8 { get; set; }
        public string sCol9 { get; set; }
        public string sCol10 { get; set; }
        public System.DateTimeOffset NoticeDurationFrom { get; set; }
        public System.DateTimeOffset NoticeDurationTo { get; set; }
        public int OrderNumber { get; set; }
        public string CreateAdminID { get; set; }
        public string HideYN { get; set; }
        public string DeleteYN { get; set; }
        public System.DateTimeOffset CreatedAt { get; set; }
        public System.DateTimeOffset UpdatedAt { get; set; }
        public string DataFromRegion { get; set; }
        public System.DateTimeOffset DataFromRegionDT { get; set; }
    }
}
