//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudBread_Admin_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServerInfo
    {
        public string InfoID { get; set; }
        public string FEServerLists { get; set; }
        public string SocketServerLists { get; set; }
        public string Version { get; set; }
        public string ResourceLink { get; set; }
        public string EULAText { get; set; }
        public string sCol1 { get; set; }
        public string sCol2 { get; set; }
        public string sCol3 { get; set; }
        public string sCol4 { get; set; }
        public string sCol5 { get; set; }
        public System.DateTimeOffset CreatedAt { get; set; }
        public System.DateTimeOffset UpdatedAt { get; set; }
        public string DataFromRegion { get; set; }
        public System.DateTimeOffset DataFromRegionDT { get; set; }
    }
}
