
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CloudBreadAdminWeb
{

using System;
    using System.Collections.Generic;
    
public partial class StatsData
{

    public string StatID { get; set; }

    public string CategoryName { get; set; }

    public long CountNum { get; set; }

    public string Fields { get; set; }

    public System.DateTimeOffset CreatedAt { get; set; }

    public System.DateTimeOffset UpdatedAt { get; set; }

    public System.DateTimeOffset DataFromRegionDT { get; set; }

    public string DataFromRegion { get; set; }

}

}
