export const FIND_RESOURCES_REQUEST = 'FIND_RESOURCES_REQUEST';
export const FIND_RESOURCES_SUCCESS = 'FIND_RESOURCES_SUCCESS';
export const FIND_RESOURCES_ERROR = 'FIND_RESOURCES_ERROR';

export const FIND_RESOURCE_ONE_REQUEST = 'FIND_RESOURCE_ONE_REQUEST';
export const FIND_RESOURCE_ONE_SUCCESS = 'FIND_RESOURCE_ONE_SUCCESS';
export const FIND_RESOURCE_ONE_ERROR = 'FIND_RESOURCE_ONE_ERROR';

export const EDIT_RESOURCE = 'EDIT_RESOURCE';

export const UPDATE_RESOURCE_REQUEST = 'UPDATE_RESOURCE_REQUEST';
export const UPDATE_RESOURCE_SUCCESS = 'UPDATE_RESOURCE_SUCCESS';
export const UPDATE_RESOURCE_ERROR = 'UPDATE_RESOURCE_ERROR';

export const DELETE_RESOURCE_REQUEST = 'DELETE_RESOURCE_REQUEST';
export const DELETE_RESOURCE_SUCCESS = 'DELETE_RESOURCE_SUCCESS';
export const DELETE_RESOURCE_ERROR = 'DELETE_RESOURCE_ERROR';

export const START_EDIT_RESOURCE = 'START_EDIT_RESOURCE';
export const STOP_EDIT_RESOURCE = 'STOP_EDIT_RESOURCE';

export const REMOVE_RESOURCE_ITEM = 'REMOVE_RESOURCE_ITEM';

export const START_FIND_RESOURCE = 'START_FIND_RESOURCE';
export const STOP_FIND_RESOURCE = 'STOP_FIND_RESOURCE';
