export const AUTHENTICATE_SUCCESS = 'AUTHENTICATE_SUCCESS';
export const AUTHENTICATE_ERROR = 'AUTHENTICATE_ERROR';
export const AUTHENTICATE_REQUEST = 'AUTHENTICATE_PENDING';
export const SIGNOUT = 'SINGOUT';
